from .school_views import *
from .student_views import *
from .parent_views import *
from .teacher_views import *
from .attendance_views import *
from .result_views import *
from .fee_views import *
from .summary_views import *
from .search_views import *