# Generated by Django 6.0.3 on 2026-03-24 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='parent_guardian',
            new_name='family_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='school',
            new_name='school_id',
        ),
    ]
