# Generated by Django 6.0.3 on 2026-03-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_rename_parent_guardian_student_family_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
