# Generated by Django 6.0.3 on 2026-03-25 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_student_admission_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parentguardian',
            old_name='school',
            new_name='school_id',
        ),
    ]
